----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 10/19/2025 04:09:16 PM
-- Design Name: 
-- Module Name: FIFO - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------


library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- Uncomment the following library declaration if using
-- arithmetic functions with Signed or Unsigned values
use IEEE.NUMERIC_STD.ALL;

-- Uncomment the following library declaration if instantiating
-- any Xilinx leaf cells in this code.
--library UNISIM;
--use UNISIM.VComponents.all;


entity FIFO is
    Port (
        CLK             : in  std_logic;                                  
        RST             : in  std_logic;                                 

        -- Control Signals (Generated by BIU/EU State Machines)
        WRITE_EN        : in  std_logic;                    -- Asserted when BIU has fetched a new instruction
        READ_EN         : in  std_logic;                    -- Asserted when EU is ready to execute next instruction
        FLUSH           : in  std_logic;                    -- Synchronous clear (on jump taken)

        -- Data Ports
        INSTRUCTION_IN  : in  std_logic_vector(15 downto 0);-- 16-bit instruction from memory
        INSTRUCTION_OUT : out std_logic_vector(15 downto 0);-- 16-bit instruction to Control Unit

        -- Status Flags (Crucial for BIU control)
        FULL            : out std_logic;                    -- Queue is full (BIU stops fetching)
        EMPTY           : out std_logic;                    -- Queue is empty (EU stalls)
        
        
        Q_OUT_0         : out std_logic_vector(15 downto 0);
        Q_OUT_1         : out std_logic_vector(15 downto 0);
        Q_OUT_2         : out std_logic_vector(15 downto 0)
    );
end entity FIFO;

architecture Behavioral of FIFO is

    -- FIFO depth definition: 8086 has a 6-byte queue. Using 3 instructions (6 bytes) for 16-bit data.
    constant Q_DEPTH : integer := 3;
    constant INST_WIDTH : integer := 16;

    -- Internal memory type definition
    type Q_ARRAY_T is array (0 to Q_DEPTH - 1) of std_logic_vector(INST_WIDTH-1 downto 0);

    -- State Signals (These are the actual synchronous registers)
    signal Q_MEM     : Q_ARRAY_T := (others => (others => '0'));
    signal Q_HEAD    : integer range 0 to Q_DEPTH - 1 := 0; -- Read Pointer
    signal Q_TAIL    : integer range 0 to Q_DEPTH - 1 := 0; -- Write Pointer
    signal Q_COUNT   : integer range 0 to Q_DEPTH := 0;     -- Occupancy counter

begin


    -- == 1. Synchronous Register and Memory Update Process ==
    
    Queue_Control_Process: process (CLK, rst)
        variable V_HEAD_NEXT  : integer range 0 to Q_DEPTH - 1;
        variable V_TAIL_NEXT  : integer range 0 to Q_DEPTH - 1;
        variable V_COUNT_NEXT : integer range 0 to Q_DEPTH;
    begin
        if rst = '1' then
            Q_HEAD  <= 0;
            Q_TAIL  <= 0;
            Q_COUNT <= 0;
    
        elsif rising_edge(CLK) then
            -- FLUSH
            if FLUSH = '1' then
                Q_HEAD  <= 0;
                Q_TAIL  <= 0;
                Q_COUNT <= 0;
            else
                -- --- Synchronous Logic ---
                
                -- 1. Initialize variables with current state
                V_HEAD_NEXT  := Q_HEAD;
                V_TAIL_NEXT  := Q_TAIL;
                V_COUNT_NEXT := Q_COUNT;
                
                -- 2. Check for a Read Operation
                if READ_EN = '1' and Q_COUNT > 0 then
                    V_HEAD_NEXT  := (Q_HEAD + 1) mod Q_DEPTH;
                    V_COUNT_NEXT := V_COUNT_NEXT - 1; 
                end if;
    
                -- 3. Check for a Write Operation
                if WRITE_EN = '1' and V_COUNT_NEXT < Q_DEPTH then
                    Q_MEM(Q_TAIL) <= INSTRUCTION_IN;
                    V_TAIL_NEXT   := (Q_TAIL + 1) mod Q_DEPTH;                    
                    V_COUNT_NEXT := V_COUNT_NEXT + 1;
                end if;
    
                -- 4. Update Synchronous Registers
                Q_HEAD  <= V_HEAD_NEXT;
                Q_TAIL  <= V_TAIL_NEXT;
                Q_COUNT <= V_COUNT_NEXT;
            end if;
        end if;
    end process Queue_Control_Process;


    -- == 2. Combinational Outputs (Status and Peek/Read Data) ==

    FULL  <= '1' when Q_COUNT = Q_DEPTH else '0';
    EMPTY <= '1' when Q_COUNT = 0 else '0';

    INSTRUCTION_OUT <= Q_MEM(Q_HEAD) when Q_COUNT > 0 else (others => '0');
    
    Q_OUT_0 <= Q_MEM(0);
    Q_OUT_1 <= Q_MEM(1);
    Q_OUT_2 <= Q_MEM(2);

end architecture Behavioral;


